import Header from "@/components/Header/header";
import "../styles/globals.css";
import { CountriesProvider } from "@/providers/countriesContext/countriesContext";
import type { Metadata } from "next";
import { Nunito } from "next/font/google";
import DarkThemeProvider from "@/providers/themeContext/themeContex";
import { Suspense } from "react";
import Loading from "@/components/Loading/loading";

const nunito = Nunito({ subsets: ["latin"], weight: ["400", "500", "600"] });

export const metadata: Metadata = {
  title: "Where in the world?",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="light" style={{ colorScheme: "light" }}>
      <body className={`${nunito.className} body`}>
        <CountriesProvider>
          <Suspense fallback={<Loading />}>
            <DarkThemeProvider>
              <Header />

              {children}
            </DarkThemeProvider>
          </Suspense>
        </CountriesProvider>
      </body>
    </html>
  );
}
